import type { Metadata } from "next";
import { Poppins, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import NavbarDemo from "@/components/elements/NavbarDemo";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>

      <body
        className={`${poppins.variable} ${geistMono.variable} antialiased`}
      >

        <ThemeProvider 
          attribute={"class"} 
          defaultTheme="dark"
          enableSystem={false}
        > 
          <NavbarDemo/>    
          {children}
        </ThemeProvider>

      </body>

    </html>
  );
}
